# Generated by Django 5.1.7 on 2026-03-27 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("view", "Viewed"),
                            ("export", "Exported"),
                            ("import", "Imported"),
                            ("share", "Shared"),
                            ("invite", "Invited"),
                            ("accept", "Accepted"),
                            ("decline", "Declined"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("description", models.TextField()),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="activity_ac_project_be469b_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="activity_ac_user_id_4cbf84_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activity_ac_content_cf269d_idx",
                    ),
                    models.Index(
                        fields=["action"], name="activity_ac_action_0385c4_idx"
                    ),
                ],
            },
        ),
    ]
