# Generated by Django 5.1.7 on 2026-03-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to='documents/%Y/%m/'),
        ),
    ]
